### ISSUE TITLE
Support CBOR in foxglove studio visualizer

### ISSUE THREAD

**Issue by therishidesai** [foxglove/community#330]
I want to use CBOR as the serialization/deserialization method but when I use the "cbor" message encoding type in my MCAP file the foxglove studio visualizer errors with the following:

```
Error: Unsupported encoding cbor
    at parseChannel (https://studio.foxglove.dev/1023.b8837902683ffb518450.js:1:7731)
    at McapIndexedIterableSource.initialize (https://studio.foxglove.dev/4766.761276315d65092c2625.js:1:1915)
    at McapIterableSource.initialize (https://studio.foxglove.dev/4766.761276315d65092c2625.js:1:11413)
    at async WorkerIterableSourceWorker.initialize (https://studio.foxglove.dev/4126.a9f9b288f40cab96776f.js:1:20965)
```

**Comment by jtbandes** [comment]
See also: https://github.com/json-schema-org/json-schema-spec/issues/6
